configfile: "config/config_mcclintock.yaml"

notification_email=config["email"]


include:    "rules/common.smk"
include:    "rules/alignment.smk"
include:    "rules/sv_call.smk"
include:    "rules/phasing.smk"
include:    "rules/annotation.smk"
include:    "rules/cleanup_cleaner.smk"
include:    "rules/qc_alignment.smk"
include:    "rules/adaptive_sampling.smk"
include:    "rules/cnv_call.smk"
include:    "rules/cDNA.smk"



rule all:
    input:
        get_targets_new
        #get_targets_transcriptome

onsuccess: shell("""echo "alignment snake has stopped after succesfully creating all targets" | mail -s "{PROJECT} alignment workflow complete" {notification_email}""")
    
onerror: shell( """
logfile=$( ls -t .snakemake/log | head -n1)
echo "$(grep -A 10 Error $logfile)" | mail -s "{PROJECT} alignment fail" {notification_email}""")