configfile: "config/config_mcclintock.yaml"


include:    "rules/common.smk"
include:    "rules/copy_inputs.smk"
include:    "rules/alignment.smk"
include:    "rules/sv_call.smk"
include:    "rules/phasing.smk"
include:    "rules/annotation.smk"
#include:    "rules/multisample.smk"
#include:    "rules/multisample_catchup.smk"
#include:    "rules/phaseMulti.smk"
include:    "rules/cleanup_cleaner.smk"
include:    "rules/qc_alignment.smk"
include:    "rules/adaptive_sampling.smk"
include:    "rules/cnv_call.smk"



rule all:
    input:
        #get_final_targets_all # this one  will attempt to align/multisample everything
        #get_final_targets # this one reads from the target file defined in the config file.
        #get_only_multisample_targets # this one only runs multisample and temporarily copies the needed bam files to Franklin.
        "M1675-NP-WGS-missingVariant-A00028_lactic_acidosis-5mCG_5hmCG-Pb/M1675-NP-WGS-missingVariant-A00028_lactic_acidosis-5mCG_5hmCG-Pb.clair3.phased.vep.af_lt_1.csv"